// <auto-generated />
using BlzTest.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlzTest.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200812133924_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlzTest.Data.Model.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FishList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LakeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LakeId");

                    b.ToTable("Fish1");
                });

            modelBuilder.Entity("BlzTest.Data.Model.Lake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DnrNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EcoRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSentinel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LakeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lake");
                });

            modelBuilder.Entity("BlzTest.Data.Models.FishLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FishList")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fish");
                });

            modelBuilder.Entity("BlzTest.Data.Model.Fish", b =>
                {
                    b.HasOne("BlzTest.Data.Model.Lake", null)
                        .WithMany("FishList")
                        .HasForeignKey("LakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
